### ISSUE TITLE
error while building from source:  error: ‘async_queue’ does not name a type

### ISSUE THREAD

**Issue by cogmeta** [arrayfire/threads#4]
[  1%] Building CXX object src/backend/cpu/CMakeFiles/afcpu.dir/Array.cpp.o
In file included from /home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/platform.hpp:12:0,
                 from /home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/Array.hpp:16,
                 from /home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/Array.cpp:10:
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp:42:9: error: ‘async_queue’ does not name a type
 typedef async_queue queue_impl;
         ^
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp:85:5: error: ‘queue_impl’ does not name a type
     queue_impl aQueue;
     ^
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp: In member function ‘void cpu::queue::enqueue(F, Args ...)’:
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp:64:13: error: ‘aQueue’ was not declared in this scope
             aQueue.enqueue(func, toParam(args)...);
             ^
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp: In member function ‘void cpu::queue::sync()’:
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp:75:26: error: ‘aQueue’ was not declared in this scope
         if (!sync_calls) aQueue.sync();
                          ^
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp: In member function ‘bool cpu::queue::is_worker() const’:
/home/psasatte/speech-res/w2l_cli/src/arrayfire/src/backend/cpu/queue.hpp:79:32: error: ‘aQueue’ was not declared in this scope
         return (!sync_calls) ? aQueue.is_worker() : false;
                                ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’
src/backend/cpu/CMakeFiles/afcpu.dir/build.make:62: recipe for target 'src/backend/cpu/CMakeFiles/afcpu.dir/Array.cpp.o' failed
make[2]: *** [src/backend/cpu/CMakeFiles/afcpu.dir/Array.cpp.o] Error 1
CMakeFiles/Makefile2:1319: recipe for target 'src/backend/cpu/CMakeFiles/afcpu.dir/all' failed
make[1]: *** [src/backend/cpu/CMakeFiles/afcpu.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by umar456** [comment]
I think you are missing submodules. Make sure you use the recursive flag when you clone or run the following commands in the ArrayFire repo:

```
git submodule init;
git submodule update;
```
